### PR TITLE
Guide: Plex setup

### PR DESCRIPTION
**Pull request by Venezia1337**
hotfix for plex issues connected with Homarr dashboard
 
Guide: Plex setup

### CODE REVIEW

**Comment by ajnart** [comment]
I'm not sure where this is supposed to fit on the page. I am pretty sure the way you did it wouldn't create any new webpage. 

But it raises the following question: @manuel-rw do you think we could have some kind of community-guides page where we kind of throw all the user-made guides ?
It Could be beneficial to promote people making videos about homarr or guides like these 

Anyways thanks for your submission @Venezia1337 , we'll read it and find a place to fit it that would be make sense as part of homarr's documentation

**Comment by manuel-rw** [comment]
Separate page or FAQ page I'd say

**Comment by ajnart** [comment]
@Venezia1337 This is getting a bit stale, would you mind moving it to somewhere else as per @manuel-rw comment ?

**Comment by ajnart** [comment]
Closing because not updated

**Pull request closed without merging**
